name: Daily Tests with Energy Measurement
run-name: Scheduled - DEV Branch
on: workflow_dispatch
jobs:
  run-tests:
    name: Teste
    runs-on: ubuntu-latest
    permissions:
        actions: read
    steps:
      - name: Initialize Energy Estimation
        id: step1
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: start-measurement
          #display-graph: false

      - name: 'Checkout repository'
        id: step2
        uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: 'true'

      - name: Checkout Repo Measurement
        id: step3
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'repo checkout'
          send-data: false

      - name: setup python
        id: step4
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Setup Python Measurment
        id: step5
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'python setup'
          send-data: false

      - name: Show Energy Results
        id: step6
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: display-results
          send-data: false
          #display-graph: false
          
      - name: Print goodbye
        id: step7
        run: echo "${{ toJSON(steps.step6.outputs.data-total-json) }}"
          
