name: Daily Tests with Energy Measurement
run-name: Scheduled - DEV Branch
on: workflow_dispatch
jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
        actions: read
    steps:
      - name: Initialize Energy Estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: start-measurement
          #display-graph: false

      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: 'true'

      - name: Checkout Repo Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'repo checkout'
          send-data: false

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Setup Python Measurment
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'python setup'
          send-data: false

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: display-results
          send-data: false
          #display-graph: false
          
