name: Daily Tests with Energy Measurement
run-name: Scheduled - DEV Branch
on: workflow_dispatch
jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
        actions: read
    steps:
      - name: Initialize Energy Estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: start-measurement

      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: 'true'

      - name: Checkout Repo Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'repo checkout'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: pip install
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Setup Python Measurment
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'python setup'

      - name: Run Tests
        shell: bash
        run: |
          pytest

      - name: Tests measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'pytest'

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: display-results
