name: Daily Tests with Energy Measurement
run-name: Scheduled - DEV Branch
on: workflow_dispatch
jobs:
  run-tests:
    name: Teste
    runs-on: ubuntu-latest
    permissions:
        actions: read
    outputs:
      energy-estimation: ${{ toJSON(steps.step9.outputs.data-total-json) }}
    steps:
      - name: Initialize Energy Estimation
        id: step1
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: start-measurement
          #display-graph: false

      #- name: Checkout Repo Measurement
      #  id: step2
      #  uses: green-coding-berlin/eco-ci-energy-estimation@v1
      #  with:
      #    task: get-measurement
      #    label: 'repo checkout'
      #    send-data: false

      - name: setup python
        id: step3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install NodeJS
        id: step5
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: 'Checkout repository'
        id: step4
        uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: 'true'
      - name: Install dependencies
        id: step6
        run: npm install
      - name: Run tests
        id: step7
        run: npm test

    
      - name: Setup Python Measurment
        id: step8
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          label: 'python setup'
          send-data: false

      - name: Create Energy Results
        id: step9
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: display-results
          send-data: false
          #display-graph: false
          
  send-ci-energy-estimation:
    name: Send Ci Energy Estimation
    runs-on: ubuntu-latest
    needs: run-tests
    steps: 
      - name: Print JSON Energy Results
        id: step7
        run: echo "${{ toJSON( needs.run-tests.outputs.energy-estimation ) }}"
